### ISSUE TITLE
[DEPR]: credentials-themes

### ISSUE THREAD

**Issue by deborahgu** [openedx/credentials-themes#795]
### Proposal Date

2024-04-02

### Ticket Acceptance Date

 2024-04-18

### Technology Removal Date

2024-05-20

### First Open edX Named Release Without This Functionality

Sumac

### Rationale

It is our belief that only 2U is using credentials-themes and it should be deprecated and moved into a 2U fork.

### Removal

* The repo will be forked to `edx` and archived from `openedx`
* the requirement to install the repo will be removed from `openedx/credentials`

### Replacement

This will not be replaced,  because nobody outside 2U is using it.

**Comment by dyudyunov** [comment]
Hi
We at RG are using credentials-themes for styling/modifying the records pages and program certificates.

Starting from the Quince release a lot (or maybe all of them) of Django templates (aka legacy frontend) were removed from the credentials repo, so the theme became useless in all cases except one: the templates for **program certificates** are still added through it.

Maybe I'm missing something and program certificates could be added/modified/styled in another way?

**Comment by deborahgu** [comment]
Ah thanks! Can I ask how you're using it? the credentials-themes repo is currently all branded edx-org templates -- or are you installing a fork of it?

https://github.com/openedx/credentials-themes/blob/master/edx_credentials_themes/templates/edx.org/credentials/programs/professional-certificate/certificate.html#L1

**Comment by dyudyunov** [comment]
We are using the fresh version of the repo, then fork it and update with needed theme changes. 

As I said, we were going to get rid of the credentials-theme dependency starting from the Quince release but left it for now because of the Program certificates

**Comment by deborahgu** [comment]
that makes perfect sense, thank you. I will close the DEPR and maybe we can  start a conversation about the styling of Program certs on openedx slack!
